R"CPP_RAW_STRING(//"
// Copyright (c) 2020-2024 Sami Väisänen

// the SDF (signed distance field) 2D shape functions
// for any point p that is outside the shape the distance will be positive.
// for any point p that is inside the shape the distance will be negative.
// for any point p that is on the edge/surface of the shape distance will be zero.

// Based off on work by Inigo Quilez, MIT license (c) Copyright Inigo Quilez
// https://iquilezles.org/articles/distfunctions2d/
// https://iquilezles.org/articles/

// @types

struct SDF_Shape {
  uint shape;
  uint fill_mode;
  float outline_width;
  float corner_radius;
  float aspect_ratio;
};

// @code

// top half = 0
// right half = 1
// bottom half = 2
// left half = 3
float SemiCircle_SDF(vec2 frag_p, vec2 circle_p, float radius, int circle_half) {
  if (circle_half == 0) {
    if (frag_p.y > circle_p.y)
      return 1.0;
  }

  if (circle_half == 1) {
    if (frag_p.x < circle_p.x)
      return 1.0;
  }

  if (circle_half == 2) {
    if (frag_p.y < circle_p.y)
      return 1.0;
  }

  if (circle_half == 3) {
    if (frag_p.x > circle_p.x)
      return 1.0;
  }

  float d = length(circle_p - frag_p);
  return d - radius;
}

float Circle_SDF(vec2 frag_p, vec2 circle_p, float radius) {
  float d = length(circle_p - frag_p);
  return d - radius;
}

// (c) Inigo Quilez, MIT license
// https://iquilezles.org/articles/distfunctions2d/
float Box_SDF(vec2 frag_p, vec2 box_p, float width, float height) {
  vec2 p = frag_p - box_p;
  vec2 b = vec2(width*0.5, height*0.5);

  vec2 d = abs(p)-b;
  return length(max(d,0.0)) + min(max(d.x,d.y),0.0);
}

// left edge  = 0
// right edge = 1
// top_edge   = 2
// bottom edge = 3
float Edge_SDF(vec2 frag_p, vec2 edge_p, float width, float height, int edge) {
  float edge_left = edge_p.x - width*0.5;
  float edge_right = edge_p.x + width*0.5;
  float edge_top = edge_p.y - height*0.5;
  float edge_bottom = edge_p.y + height*0.5;

  if (edge == 0 || edge == 1) {
    if (frag_p.y < edge_top || frag_p.y > edge_bottom)
      return 1.0;
  }
  if (edge == 2 || edge == 3) {
    if (frag_p.x < edge_left || frag_p.x > edge_right)
      return 1.0;
  }

  if (edge == 0) {
    if (frag_p.x > edge_right)
      return 1.0;
    return edge_left - frag_p.x;
  }

  if (edge == 1) {
    if (frag_p.x < edge_left)
      return 1.0;
    return frag_p.x - edge_right;
  }

  if (edge == 2) {
    if (frag_p.y > edge_bottom)
      return 1.0;
    return edge_top - frag_p.y;
  }

  if (edge == 3) {
    if (frag_p.y < edge_top)
      return 1.0;
    return frag_p.y - edge_bottom;
  }
  return 0.0;
}

// (c) Inigo Quilez, MIT license
// https://iquilezles.org/articles/distfunctions2d/
float RoundBox_SDF(vec2 frag_p, vec2 box_p, float radius, float width, float height) {
  vec2 d = abs(frag_p - box_p) - vec2(width*0.5, height*0.5) + radius;
  return length(max(d, 0.0)) + min(max(d.x, d.y), 0.0) - radius;
}

// Generated by Claude based on simple_shape.cpp
// Parallelogram with a fixed horizontal skew of 0.2 (20% of width),
// matching the geometry in simple_shape.cpp:
//   top-left=(-hw+sk,-hh), top-right=(hw,-hh),
//   bottom-right=(hw-sk,hh), bottom-left=(-hw,hh)  where sk = 0.2*width
float Parallelogram_SDF(vec2 frag_p, vec2 pos, float width, float height) {
  float hw = width  * 0.5;
  float hh = height * 0.5;
  float sk = 0.2 * width;

  vec2 p = frag_p - pos;

  // Top and bottom horizontal edges (outward normals: (0,-1) and (0,+1)).
  float d_top    = -(p.y + hh);
  float d_bottom =   p.y - hh;

  // Left and right slanted edges.
  // Right edge direction: (-sk, 2hh), outward normal: (2hh,  sk) / len_side
  // Left  edge direction: ( sk,-2hh), outward normal: (-2hh,-sk) / len_side
  float len_side = sqrt(4.0*hh*hh + sk*sk);
  float d_right = ( 2.0*hh*(p.x - hw) + sk*(p.y + hh)) / len_side;
  float d_left  = (-2.0*hh*(p.x + hw) - sk*(p.y - hh)) / len_side;

  return max(max(d_top, d_bottom), max(d_right, d_left));
}

// (c) Sami Väisänen
float Horizontal_Capsule_SDF(vec2 frag_p, vec2 pos, float radius, float width) {
  float shape_width = width;
  float shape_height = radius*2.0;

  float left = pos.x - width*0.5 + radius;
  float right = pos.x + width*0.5 - radius;

  float left_end = SemiCircle_SDF(frag_p, vec2(left, pos.y), radius, 3);
  float right_end = SemiCircle_SDF(frag_p, vec2(right, pos.y), radius, 1);

  float box_width = shape_width - 2.0*radius;
  float box_height = shape_height*0.5;

  float top_edge = Edge_SDF(frag_p, pos + vec2(0.0, -box_height*0.5), box_width, box_height, 2);
  float bottom_edge = Edge_SDF(frag_p, pos + vec2(0.0, +box_height*0.5), box_width, box_height, 3);

  return min(min(left_end, right_end),
               min(top_edge, bottom_edge));
}

// (c) Sami Väisänen
float Vertical_Capsule_SDF(vec2 frag_p, vec2 pos, float radius, float height) {
  float shape_width  = radius*2.0;
  float shape_height = height;

  float top    = pos.y - height*0.5 + radius;
  float bottom  = pos.y + height*0.5 - radius;

  float top_end    = SemiCircle_SDF(frag_p, vec2(pos.x, top),    radius, 0);
  float bottom_end = SemiCircle_SDF(frag_p, vec2(pos.x, bottom), radius, 2);

  float box_width  = shape_width*0.5;
  float box_height = shape_height - 2.0*radius;

  float left_edge  = Edge_SDF(frag_p, pos + vec2(-box_width*0.5, 0.0), box_width, box_height, 0);
  float right_edge = Edge_SDF(frag_p, pos + vec2(+box_width*0.5, 0.0), box_width, box_height, 1);

  return min(min(top_end, bottom_end),
               min(left_edge, right_edge));
}

// given a shape calculate the alpha value based on SDF
float Calculate_SDF_Alpha(in SDF_Shape shape, vec2 frag_p) {

  // when rendering an outline the outline is inside the shape's bounds.
  //
  // => shape's surface is in the middle of the outline
  //   => with smoothing half the outline is outside the object
  //   => with smoothing half the outline is inside the object
  //   => shapes size is 1.0 - 2.0*half the outline width = 1.0 - outline_width

  float shape_width;
  float shape_height;
  float distance = 1.0;

  if (shape.shape == SDF_SHAPE_VERTICAL_CAPSULE) {
    shape_width  = min(1.0, 1.0 / shape.aspect_ratio) - shape.outline_width;
    shape_height = min(1.0, shape.aspect_ratio)       - shape.outline_width;
  } else {
    shape_width  = min(1.0, shape.aspect_ratio)       - shape.outline_width;
    shape_height = min(1.0, 1.0 / shape.aspect_ratio) - shape.outline_width;
  }

  vec2 shape_pos = vec2(0.0, 0.0);

  if (shape.shape == SDF_SHAPE_CIRCLE) {
    distance = Circle_SDF(frag_p, shape_pos, min(shape_width, shape_height)*0.5);
  } if (shape.shape == SDF_SHAPE_RECT) {
    distance = Box_SDF(frag_p, shape_pos, shape_width, shape_height);
  } else if (shape.shape == SDF_SHAPE_ROUND_RECT) {
    distance = RoundBox_SDF(frag_p, shape_pos, shape.corner_radius, shape_width, shape_height);
  } else if (shape.shape == SDF_SHAPE_PARALLELOGRAM) {
    distance = Parallelogram_SDF(frag_p, shape_pos, shape_width, shape_height);
  } else if (shape.shape == SDF_SHAPE_HORIZONTAL_CAPSULE) {
    distance = Horizontal_Capsule_SDF(frag_p, shape_pos, shape.corner_radius, shape_width);
  } else if (shape.shape == SDF_SHAPE_VERTICAL_CAPSULE) {
    distance = Vertical_Capsule_SDF(frag_p, shape_pos, shape.corner_radius, shape_height);
  }

  if (shape.fill_mode == SDF_FILL_MODE_OUTLINE) {

    // fwidth is the sum of the magnitudes of change in distance
    // on both X and Y axis. (fwidth = abs(dFdx(v)) + abs(dFdy(v)))
    //
    // fwidth(distance) answers: "how much does distance change per pixel here?"
    float px = fwidth(distance);

    float outline_half = shape.outline_width*0.5;

    // Linear coverage: 1.0 at the outline center (distance=0), 0.5 at the
    // outline edge (abs(distance)=outline_half), 0.0 one pixel outside.
    // Handles sub-pixel outlines naturally without a separate clamp.
    float alpha = clamp((outline_half - abs(distance)) / px + 0.5, 0.0, 1.0);
    return alpha;
  }

  // todo: fill mode if needed, probably not really since we
  // can just a polygonal shape rasterization and it will be
  // cheaper too..

  return 0.0;
}

)CPP_RAW_STRING"
