wc -l `find base/ -name *.h` \
`find base/ -name *.cpp` \
`find audio/ -name *.h` \
`find audio/ -name *.cpp` \
`find data/ -name *.h` \
`find data/ -name *.cpp` \
`find editor/ -name *.h` \
`find editor/ -name *.cpp` \
`find emscripten/ -name *.h` \
`find emscripten/ -name *.cpp` \
`find engine/ -name *.h` \
`find engine/ -name *.cpp` \
`find game/ -name *.h` \
`find game/ -name *.cpp` \
`find graphics/ -name *.h` \
`find graphics/ -name *.cpp` \
`find uikit/ -name *.h` \
`find uikit/ -name *.cpp` \
`find wdk/wdk/ -name *.h` \
`find wdk/wdk/ -name *.cpp` \